/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Project example
 * The project API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

export type ErrorObjectErrorsItem = { [key: string]: unknown };

/**
 * Inner error object.  This is not strictly required, but can provide additional context about the error.
 */
export type ErrorObjectInnerError = { [key: string]: unknown };

export interface ErrorObject {
  /** Error code */
  code: string;
  /** Error message */
  message: string;
  /** Additional error details or fields.  This is not strictly required, but can be used to provide more context about the error. */
  errors?: ErrorObjectErrorsItem[];
  /** Inner error object.  This is not strictly required, but can provide additional context about the error. */
  innerError?: ErrorObjectInnerError;
}

export interface CommonExceptionDto {
  /** Error object containing exception details */
  error: ErrorObject;
}

export interface PaginatedDto { [key: string]: unknown }

/**
 * The main value or entity returned by the API.
 */
export type SingleObjectDtoValue = { [key: string]: unknown };

export interface SingleObjectDto {
  /** The main value or entity returned by the API. */
  value: SingleObjectDtoValue;
}

export interface ProjectEntity {
  /** Project status */
  projectStatus: string;
  /** Project name */
  name: string;
  /**
     * The age of the Project
     * @minimum 1
     */
  age: number;
  /** The breed of the Project */
  breed: string;
  /** Nicknames for the Project */
  nicknames?: string[];
  /** The date when the project was created */
  createdDateTime: string;
  /** The date when the project was last updated */
  lastModifiedDateTime: string;
}

/**
 * Description of the CreateProjectDto schema
 */
export interface CreateProjectDto {
  /** Project status */
  projectStatus: string;
  /** Project name */
  name: string;
  /**
     * The age of the Project
     * @minimum 1
     */
  age: number;
  /** The breed of the Project */
  breed: string;
  /** Nicknames for the Project */
  nicknames?: string[];
}

export type ProjectStatus = typeof ProjectStatus[keyof typeof ProjectStatus];


export const ProjectStatus = {
  Draft: 'Draft',
  Submitted: 'Submitted',
  Ready_for_IT_Supplement: 'Ready for IT Supplement',
} as const;

export interface UpdateProjectDto {
  /** Project status */
  projectStatus?: string;
  /** Project name */
  name?: string;
  /**
     * The age of the Project
     * @minimum 1
     */
  age?: number;
  /** The breed of the Project */
  breed?: string;
  /** Nicknames for the Project */
  nicknames?: string[];
}

export interface Note {
  /** The unique identifier of the note */
  id: number;
  /** The text content of the note */
  text: string;
  /** The ID of the folder this note belongs to */
  folderId: number;
  /** The date and time when the note was created */
  createdAt: string;
}

/**
 * Data Transfer Object for creating a note
 */
export interface CreateNoteDto {
  /** The text content of the note */
  text: string;
  /** The ID of the folder to which the note belongs */
  folderId: number;
}

export interface UpdateNoteDto {
  /** The text content of the note */
  text?: string;
  /** The ID of the folder to which the note belongs */
  folderId?: number;
}

export type CatsControllerCreate201 = SingleObjectDto & {
  value?: ProjectEntity;
};

export type CatsControllerFindAllParams = {
/**
 * Start date filter (ISO 8601)
 */
startDate?: string;
/**
 * End date filter (ISO 8601)
 */
endDate?: string;
/**
 * Filtered by project status
 */
projectStatus?: ProjectStatus;
/**
 * Order by fields, e.g. [updatedDateTime desc, name asc]
 */
orderBy?: string[];
/**
 * The number of items to skip before starting to collect the result
 * @minimum 0
 * @maximum 500
 */
offset?: number;
/**
 * The numbers of items to return
 * @minimum 1
 * @maximum 50
 */
limit?: number;
/**
 * If true, return total count of items
 */
count?: boolean;
};

export type CatsControllerFindAll200 = PaginatedDto & {
  value?: ProjectEntity[];
};

export type CreateNote201 = SingleObjectDto & {
  value?: Note;
};

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type appControllerGetHelloResponse200 = {
  data: void
  status: 200
}

export type appControllerGetHelloResponse400 = {
  data: CommonExceptionDto
  status: 400
}

export type appControllerGetHelloResponse422 = {
  data: CommonExceptionDto
  status: 422
}

export type appControllerGetHelloResponseSuccess = (appControllerGetHelloResponse200) & {
  headers: Headers;
};
export type appControllerGetHelloResponseError = (appControllerGetHelloResponse400 | appControllerGetHelloResponse422) & {
  headers: Headers;
};

export type appControllerGetHelloResponse = (appControllerGetHelloResponseSuccess | appControllerGetHelloResponseError)

export const getAppControllerGetHelloUrl = () => {




  return `http://localhost:3000/`
}

export const appControllerGetHello = async ( options?: RequestInit): Promise<appControllerGetHelloResponse> => {

  const res = await fetch(getAppControllerGetHelloUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: appControllerGetHelloResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as appControllerGetHelloResponse
}





export const getAppControllerGetHelloQueryKey = () => {
    return [
    `http://localhost:3000/`
    ] as const;
    }


export const getAppControllerGetHelloQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = CommonExceptionDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppControllerGetHelloQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetHello>>> = ({ signal }) => appControllerGetHello({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AppControllerGetHelloQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetHello>>>
export type AppControllerGetHelloQueryError = CommonExceptionDto


export function useAppControllerGetHello<TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = CommonExceptionDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetHello>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetHello>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppControllerGetHello<TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = CommonExceptionDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetHello>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetHello>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAppControllerGetHello<TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = CommonExceptionDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAppControllerGetHello<TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = CommonExceptionDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAppControllerGetHelloQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type catsControllerCreateResponse201 = {
  data: CatsControllerCreate201
  status: 201
}

export type catsControllerCreateResponse400 = {
  data: CommonExceptionDto
  status: 400
}

export type catsControllerCreateResponse422 = {
  data: CommonExceptionDto
  status: 422
}

export type catsControllerCreateResponseSuccess = (catsControllerCreateResponse201) & {
  headers: Headers;
};
export type catsControllerCreateResponseError = (catsControllerCreateResponse400 | catsControllerCreateResponse422) & {
  headers: Headers;
};

export type catsControllerCreateResponse = (catsControllerCreateResponseSuccess | catsControllerCreateResponseError)

export const getCatsControllerCreateUrl = () => {




  return `http://localhost:3000/projects`
}

export const catsControllerCreate = async (createProjectDto: CreateProjectDto, options?: RequestInit): Promise<catsControllerCreateResponse> => {

  const res = await fetch(getCatsControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createProjectDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: catsControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as catsControllerCreateResponse
}





export const getCatsControllerCreateMutationOptions = <TError = CommonExceptionDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catsControllerCreate>>, TError,{data: CreateProjectDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof catsControllerCreate>>, TError,{data: CreateProjectDto}, TContext> => {

const mutationKey = ['catsControllerCreate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catsControllerCreate>>, {data: CreateProjectDto}> = (props) => {
          const {data} = props ?? {};

          return  catsControllerCreate(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof catsControllerCreate>>>
    export type CatsControllerCreateMutationBody = CreateProjectDto
    export type CatsControllerCreateMutationError = CommonExceptionDto

    export const useCatsControllerCreate = <TError = CommonExceptionDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catsControllerCreate>>, TError,{data: CreateProjectDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catsControllerCreate>>,
        TError,
        {data: CreateProjectDto},
        TContext
      > => {
      return useMutation(getCatsControllerCreateMutationOptions(options), queryClient);
    }

export type catsControllerFindAllResponse200 = {
  data: CatsControllerFindAll200
  status: 200
}

export type catsControllerFindAllResponse400 = {
  data: CommonExceptionDto
  status: 400
}

export type catsControllerFindAllResponse422 = {
  data: CommonExceptionDto
  status: 422
}

export type catsControllerFindAllResponseSuccess = (catsControllerFindAllResponse200) & {
  headers: Headers;
};
export type catsControllerFindAllResponseError = (catsControllerFindAllResponse400 | catsControllerFindAllResponse422) & {
  headers: Headers;
};

export type catsControllerFindAllResponse = (catsControllerFindAllResponseSuccess | catsControllerFindAllResponseError)

export const getCatsControllerFindAllUrl = (params?: CatsControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["orderBy"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/projects?${stringifiedParams}` : `http://localhost:3000/projects`
}

export const catsControllerFindAll = async (params?: CatsControllerFindAllParams, options?: RequestInit): Promise<catsControllerFindAllResponse> => {

  const res = await fetch(getCatsControllerFindAllUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: catsControllerFindAllResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as catsControllerFindAllResponse
}





export const getCatsControllerFindAllQueryKey = (params?: CatsControllerFindAllParams,) => {
    return [
    `http://localhost:3000/projects`, ...(params ? [params] : [])
    ] as const;
    }


export const getCatsControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof catsControllerFindAll>>, TError = CommonExceptionDto>(params?: CatsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catsControllerFindAll>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatsControllerFindAllQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catsControllerFindAll>>> = ({ signal }) => catsControllerFindAll(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catsControllerFindAll>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatsControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof catsControllerFindAll>>>
export type CatsControllerFindAllQueryError = CommonExceptionDto


export function useCatsControllerFindAll<TData = Awaited<ReturnType<typeof catsControllerFindAll>>, TError = CommonExceptionDto>(
 params: undefined |  CatsControllerFindAllParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catsControllerFindAll>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof catsControllerFindAll>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatsControllerFindAll<TData = Awaited<ReturnType<typeof catsControllerFindAll>>, TError = CommonExceptionDto>(
 params?: CatsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catsControllerFindAll>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof catsControllerFindAll>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatsControllerFindAll<TData = Awaited<ReturnType<typeof catsControllerFindAll>>, TError = CommonExceptionDto>(
 params?: CatsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catsControllerFindAll>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatsControllerFindAll<TData = Awaited<ReturnType<typeof catsControllerFindAll>>, TError = CommonExceptionDto>(
 params?: CatsControllerFindAllParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catsControllerFindAll>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatsControllerFindAllQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type catsControllerFindOneResponse200 = {
  data: void
  status: 200
}

export type catsControllerFindOneResponse400 = {
  data: CommonExceptionDto
  status: 400
}

export type catsControllerFindOneResponse422 = {
  data: CommonExceptionDto
  status: 422
}

export type catsControllerFindOneResponseSuccess = (catsControllerFindOneResponse200) & {
  headers: Headers;
};
export type catsControllerFindOneResponseError = (catsControllerFindOneResponse400 | catsControllerFindOneResponse422) & {
  headers: Headers;
};

export type catsControllerFindOneResponse = (catsControllerFindOneResponseSuccess | catsControllerFindOneResponseError)

export const getCatsControllerFindOneUrl = (projectId: string,) => {




  return `http://localhost:3000/projects/${projectId}`
}

export const catsControllerFindOne = async (projectId: string, options?: RequestInit): Promise<catsControllerFindOneResponse> => {

  const res = await fetch(getCatsControllerFindOneUrl(projectId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: catsControllerFindOneResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as catsControllerFindOneResponse
}





export const getCatsControllerFindOneQueryKey = (projectId: string,) => {
    return [
    `http://localhost:3000/projects/${projectId}`
    ] as const;
    }


export const getCatsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof catsControllerFindOne>>, TError = CommonExceptionDto>(projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catsControllerFindOne>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCatsControllerFindOneQueryKey(projectId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof catsControllerFindOne>>> = ({ signal }) => catsControllerFindOne(projectId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof catsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CatsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof catsControllerFindOne>>>
export type CatsControllerFindOneQueryError = CommonExceptionDto


export function useCatsControllerFindOne<TData = Awaited<ReturnType<typeof catsControllerFindOne>>, TError = CommonExceptionDto>(
 projectId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof catsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof catsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof catsControllerFindOne>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatsControllerFindOne<TData = Awaited<ReturnType<typeof catsControllerFindOne>>, TError = CommonExceptionDto>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof catsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof catsControllerFindOne>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCatsControllerFindOne<TData = Awaited<ReturnType<typeof catsControllerFindOne>>, TError = CommonExceptionDto>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catsControllerFindOne>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCatsControllerFindOne<TData = Awaited<ReturnType<typeof catsControllerFindOne>>, TError = CommonExceptionDto>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof catsControllerFindOne>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCatsControllerFindOneQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type catsControllerUpdateResponse200 = {
  data: void
  status: 200
}

export type catsControllerUpdateResponse400 = {
  data: CommonExceptionDto
  status: 400
}

export type catsControllerUpdateResponse422 = {
  data: CommonExceptionDto
  status: 422
}

export type catsControllerUpdateResponseSuccess = (catsControllerUpdateResponse200) & {
  headers: Headers;
};
export type catsControllerUpdateResponseError = (catsControllerUpdateResponse400 | catsControllerUpdateResponse422) & {
  headers: Headers;
};

export type catsControllerUpdateResponse = (catsControllerUpdateResponseSuccess | catsControllerUpdateResponseError)

export const getCatsControllerUpdateUrl = (projectId: string,) => {




  return `http://localhost:3000/projects/${projectId}`
}

export const catsControllerUpdate = async (projectId: string,
    updateProjectDto: UpdateProjectDto, options?: RequestInit): Promise<catsControllerUpdateResponse> => {

  const res = await fetch(getCatsControllerUpdateUrl(projectId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateProjectDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: catsControllerUpdateResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as catsControllerUpdateResponse
}





export const getCatsControllerUpdateMutationOptions = <TError = CommonExceptionDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catsControllerUpdate>>, TError,{projectId: string;data: UpdateProjectDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof catsControllerUpdate>>, TError,{projectId: string;data: UpdateProjectDto}, TContext> => {

const mutationKey = ['catsControllerUpdate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catsControllerUpdate>>, {projectId: string;data: UpdateProjectDto}> = (props) => {
          const {projectId,data} = props ?? {};

          return  catsControllerUpdate(projectId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof catsControllerUpdate>>>
    export type CatsControllerUpdateMutationBody = UpdateProjectDto
    export type CatsControllerUpdateMutationError = CommonExceptionDto

    export const useCatsControllerUpdate = <TError = CommonExceptionDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catsControllerUpdate>>, TError,{projectId: string;data: UpdateProjectDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catsControllerUpdate>>,
        TError,
        {projectId: string;data: UpdateProjectDto},
        TContext
      > => {
      return useMutation(getCatsControllerUpdateMutationOptions(options), queryClient);
    }

export type catsControllerRemoveResponse400 = {
  data: CommonExceptionDto
  status: 400
}

export type catsControllerRemoveResponse422 = {
  data: CommonExceptionDto
  status: 422
}

;
export type catsControllerRemoveResponseError = (catsControllerRemoveResponse400 | catsControllerRemoveResponse422) & {
  headers: Headers;
};

export type catsControllerRemoveResponse = (catsControllerRemoveResponseError)

export const getCatsControllerRemoveUrl = (projectId: string,) => {




  return `http://localhost:3000/projects/${projectId}/restart`
}

export const catsControllerRemove = async (projectId: string, options?: RequestInit): Promise<catsControllerRemoveResponse> => {

  const res = await fetch(getCatsControllerRemoveUrl(projectId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: catsControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as catsControllerRemoveResponse
}





export const getCatsControllerRemoveMutationOptions = <TError = CommonExceptionDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catsControllerRemove>>, TError,{projectId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof catsControllerRemove>>, TError,{projectId: string}, TContext> => {

const mutationKey = ['catsControllerRemove'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof catsControllerRemove>>, {projectId: string}> = (props) => {
          const {projectId} = props ?? {};

          return  catsControllerRemove(projectId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CatsControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof catsControllerRemove>>>

    export type CatsControllerRemoveMutationError = CommonExceptionDto

    export const useCatsControllerRemove = <TError = CommonExceptionDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof catsControllerRemove>>, TError,{projectId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof catsControllerRemove>>,
        TError,
        {projectId: string},
        TContext
      > => {
      return useMutation(getCatsControllerRemoveMutationOptions(options), queryClient);
    }

export type createNoteResponse201 = {
  data: CreateNote201
  status: 201
}

export type createNoteResponse400 = {
  data: CommonExceptionDto
  status: 400
}

export type createNoteResponse422 = {
  data: CommonExceptionDto
  status: 422
}

export type createNoteResponseSuccess = (createNoteResponse201) & {
  headers: Headers;
};
export type createNoteResponseError = (createNoteResponse400 | createNoteResponse422) & {
  headers: Headers;
};

export type createNoteResponse = (createNoteResponseSuccess | createNoteResponseError)

export const getCreateNoteUrl = () => {




  return `http://localhost:3000/notes`
}

/**
 * @summary Create a new note
 */
export const createNote = async (createNoteDto: CreateNoteDto, options?: RequestInit): Promise<createNoteResponse> => {

  const res = await fetch(getCreateNoteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createNoteDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createNoteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createNoteResponse
}





export const getCreateNoteMutationOptions = <TError = CommonExceptionDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNote>>, TError,{data: CreateNoteDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createNote>>, TError,{data: CreateNoteDto}, TContext> => {

const mutationKey = ['createNote'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createNote>>, {data: CreateNoteDto}> = (props) => {
          const {data} = props ?? {};

          return  createNote(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateNoteMutationResult = NonNullable<Awaited<ReturnType<typeof createNote>>>
    export type CreateNoteMutationBody = CreateNoteDto
    export type CreateNoteMutationError = CommonExceptionDto

    /**
 * @summary Create a new note
 */
export const useCreateNote = <TError = CommonExceptionDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNote>>, TError,{data: CreateNoteDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createNote>>,
        TError,
        {data: CreateNoteDto},
        TContext
      > => {
      return useMutation(getCreateNoteMutationOptions(options), queryClient);
    }

export type findAllNotesResponse200 = {
  data: Note[]
  status: 200
}

export type findAllNotesResponse400 = {
  data: CommonExceptionDto
  status: 400
}

export type findAllNotesResponse422 = {
  data: CommonExceptionDto
  status: 422
}

export type findAllNotesResponseSuccess = (findAllNotesResponse200) & {
  headers: Headers;
};
export type findAllNotesResponseError = (findAllNotesResponse400 | findAllNotesResponse422) & {
  headers: Headers;
};

export type findAllNotesResponse = (findAllNotesResponseSuccess | findAllNotesResponseError)

export const getFindAllNotesUrl = () => {




  return `http://localhost:3000/notes`
}

/**
 * @summary Retrieve all notes
 */
export const findAllNotes = async ( options?: RequestInit): Promise<findAllNotesResponse> => {

  const res = await fetch(getFindAllNotesUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: findAllNotesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as findAllNotesResponse
}





export const getFindAllNotesQueryKey = () => {
    return [
    `http://localhost:3000/notes`
    ] as const;
    }


export const getFindAllNotesQueryOptions = <TData = Awaited<ReturnType<typeof findAllNotes>>, TError = CommonExceptionDto>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllNotes>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAllNotesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAllNotes>>> = ({ signal }) => findAllNotes({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAllNotes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindAllNotesQueryResult = NonNullable<Awaited<ReturnType<typeof findAllNotes>>>
export type FindAllNotesQueryError = CommonExceptionDto


export function useFindAllNotes<TData = Awaited<ReturnType<typeof findAllNotes>>, TError = CommonExceptionDto>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllNotes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllNotes>>,
          TError,
          Awaited<ReturnType<typeof findAllNotes>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllNotes<TData = Awaited<ReturnType<typeof findAllNotes>>, TError = CommonExceptionDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllNotes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllNotes>>,
          TError,
          Awaited<ReturnType<typeof findAllNotes>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllNotes<TData = Awaited<ReturnType<typeof findAllNotes>>, TError = CommonExceptionDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllNotes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieve all notes
 */

export function useFindAllNotes<TData = Awaited<ReturnType<typeof findAllNotes>>, TError = CommonExceptionDto>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllNotes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindAllNotesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type getNoteByIdResponse200 = {
  data: Note
  status: 200
}

export type getNoteByIdResponse400 = {
  data: CommonExceptionDto
  status: 400
}

export type getNoteByIdResponse422 = {
  data: CommonExceptionDto
  status: 422
}

export type getNoteByIdResponseSuccess = (getNoteByIdResponse200) & {
  headers: Headers;
};
export type getNoteByIdResponseError = (getNoteByIdResponse400 | getNoteByIdResponse422) & {
  headers: Headers;
};

export type getNoteByIdResponse = (getNoteByIdResponseSuccess | getNoteByIdResponseError)

export const getGetNoteByIdUrl = (id: string,) => {




  return `http://localhost:3000/notes/${id}`
}

/**
 * @summary Retrieve a note by ID
 */
export const getNoteById = async (id: string, options?: RequestInit): Promise<getNoteByIdResponse> => {

  const res = await fetch(getGetNoteByIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getNoteByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getNoteByIdResponse
}





export const getGetNoteByIdQueryKey = (id: string,) => {
    return [
    `http://localhost:3000/notes/${id}`
    ] as const;
    }


export const getGetNoteByIdQueryOptions = <TData = Awaited<ReturnType<typeof getNoteById>>, TError = CommonExceptionDto>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoteById>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetNoteByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getNoteById>>> = ({ signal }) => getNoteById(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getNoteById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetNoteByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getNoteById>>>
export type GetNoteByIdQueryError = CommonExceptionDto


export function useGetNoteById<TData = Awaited<ReturnType<typeof getNoteById>>, TError = CommonExceptionDto>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoteById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNoteById>>,
          TError,
          Awaited<ReturnType<typeof getNoteById>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNoteById<TData = Awaited<ReturnType<typeof getNoteById>>, TError = CommonExceptionDto>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoteById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getNoteById>>,
          TError,
          Awaited<ReturnType<typeof getNoteById>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetNoteById<TData = Awaited<ReturnType<typeof getNoteById>>, TError = CommonExceptionDto>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoteById>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Retrieve a note by ID
 */

export function useGetNoteById<TData = Awaited<ReturnType<typeof getNoteById>>, TError = CommonExceptionDto>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getNoteById>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetNoteByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export type notesControllerUpdateResponse200 = {
  data: void
  status: 200
}

export type notesControllerUpdateResponse400 = {
  data: CommonExceptionDto
  status: 400
}

export type notesControllerUpdateResponse422 = {
  data: CommonExceptionDto
  status: 422
}

export type notesControllerUpdateResponseSuccess = (notesControllerUpdateResponse200) & {
  headers: Headers;
};
export type notesControllerUpdateResponseError = (notesControllerUpdateResponse400 | notesControllerUpdateResponse422) & {
  headers: Headers;
};

export type notesControllerUpdateResponse = (notesControllerUpdateResponseSuccess | notesControllerUpdateResponseError)

export const getNotesControllerUpdateUrl = (id: string,) => {




  return `http://localhost:3000/notes/${id}`
}

export const notesControllerUpdate = async (id: string,
    updateNoteDto: UpdateNoteDto, options?: RequestInit): Promise<notesControllerUpdateResponse> => {

  const res = await fetch(getNotesControllerUpdateUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateNoteDto)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: notesControllerUpdateResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as notesControllerUpdateResponse
}





export const getNotesControllerUpdateMutationOptions = <TError = CommonExceptionDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesControllerUpdate>>, TError,{id: string;data: UpdateNoteDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof notesControllerUpdate>>, TError,{id: string;data: UpdateNoteDto}, TContext> => {

const mutationKey = ['notesControllerUpdate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notesControllerUpdate>>, {id: string;data: UpdateNoteDto}> = (props) => {
          const {id,data} = props ?? {};

          return  notesControllerUpdate(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotesControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof notesControllerUpdate>>>
    export type NotesControllerUpdateMutationBody = UpdateNoteDto
    export type NotesControllerUpdateMutationError = CommonExceptionDto

    export const useNotesControllerUpdate = <TError = CommonExceptionDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesControllerUpdate>>, TError,{id: string;data: UpdateNoteDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof notesControllerUpdate>>,
        TError,
        {id: string;data: UpdateNoteDto},
        TContext
      > => {
      return useMutation(getNotesControllerUpdateMutationOptions(options), queryClient);
    }

export type notesControllerRemoveResponse200 = {
  data: void
  status: 200
}

export type notesControllerRemoveResponse400 = {
  data: CommonExceptionDto
  status: 400
}

export type notesControllerRemoveResponse422 = {
  data: CommonExceptionDto
  status: 422
}

export type notesControllerRemoveResponseSuccess = (notesControllerRemoveResponse200) & {
  headers: Headers;
};
export type notesControllerRemoveResponseError = (notesControllerRemoveResponse400 | notesControllerRemoveResponse422) & {
  headers: Headers;
};

export type notesControllerRemoveResponse = (notesControllerRemoveResponseSuccess | notesControllerRemoveResponseError)

export const getNotesControllerRemoveUrl = (id: string,) => {




  return `http://localhost:3000/notes/${id}`
}

export const notesControllerRemove = async (id: string, options?: RequestInit): Promise<notesControllerRemoveResponse> => {

  const res = await fetch(getNotesControllerRemoveUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: notesControllerRemoveResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as notesControllerRemoveResponse
}





export const getNotesControllerRemoveMutationOptions = <TError = CommonExceptionDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesControllerRemove>>, TError,{id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof notesControllerRemove>>, TError,{id: string}, TContext> => {

const mutationKey = ['notesControllerRemove'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notesControllerRemove>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  notesControllerRemove(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotesControllerRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof notesControllerRemove>>>

    export type NotesControllerRemoveMutationError = CommonExceptionDto

    export const useNotesControllerRemove = <TError = CommonExceptionDto,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notesControllerRemove>>, TError,{id: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof notesControllerRemove>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getNotesControllerRemoveMutationOptions(options), queryClient);
    }
